spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud_sell?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
  rabbitmq:
    addresses: 192.168.209.20
    port: 5672
    username: test
    password: test
env:
  test11
